version: 2

# Group settings to apply to all groups by default, optionally being overridden later
group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^(Approved|:shipit:)'
    reject_regex: '^(Rejected)'

groups:
  general-approvers:
    conditions:
      files:
        - "*"
    required: 1
    users:
      - iclanton
      - nickpape-msft
      - pgonzal