#
# This file contains configuration flags to customize your site
#

# theme: jekyll-theme-minimal


# ---------------------------------------------------------------------------
# Theme variables for jekyll-theme-minimal
# https://github.com/pages-themes/minimal


# Name of your site (displayed in the header)
title: API Extractor

# Short bio or description (displayed in the header)
description: Build better TypeScript libraries

# Location of the Open Graph image (1200x630 recommended size, must be an absolute URL)
logo: https://api-extractor.com/images/ae-ograph.png

# "true" or "false" to indicate whether to provide a download URL
show_downloads: false

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:
# ---------------------------------------------------------------------------


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://api-extractor.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: pretty

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM

  toc_levels: 1..3

  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Settings for https://github.com/algolia/jekyll-algolia
# Our login account is: @rushbot (GitHub alias)
algolia:
  application_id: 'W2G1E3U5T0'
  index_name: 'api-extractor.com'
  search_only_api_key: 'a0ab6dfc3db0c301b0ca8e725af85641'

  # The default is to only consider <p> tags.  That also picks up <p> inside other
  # tags such as <li>.
  # But these additional tags are not containers for <p>, so we add them explicitly:
  nodes_to_index: 'p,li,h1,h2,h3'

  files_to_exclude:
    - permalinks/404.html
    - permalinks/mobile_nav.html

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-algolia # Create search index for Algolia
#  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
